### PR TITLE
add a data download timeout option for NWIS data

### LINKED ISSUE #88: Data downloads hang on HPC - let's tryCatch them
After several hundred sites download flow data, the pipeline sometimes hangs and needs to be stopped + restarted. Let's build in a tryCatch that restarts the download after a certain elapsed time

### PR DESCRIPTION
**Pull request by jds485**
Added a timeout parameter for NWIS daily and peak flow downloads. You can test that these will time out by changing the timeout parameter to 1 second.

Also added function descriptions and parameter descriptions for download functions.

Closes #88

### CODE REVIEW

**Comment by cstillwellusgs** [comment]
It was stuck at `starting site 03145000`. Didn't receive any other messages, warnings or anything.

**Comment by jds485** [comment]
Wait, `03145000` is not in the list of gages...why did it try to download that site?

**Comment by cstillwellusgs** [comment]
Well, I deleted all the .csv files and re-ran. This time... it did not try to download 03145000. So idk what the heck happened.

**Comment by cstillwellusgs** [comment]
OR I cloned your repo, ran the _targets.R script from the main branch, then realized i wasn't on your trycatch branch. So I wiped and re-cloned, made sure i was on the correct branch the entire time and now I'm re-running.

**Comment by jds485** [comment]
Okay, thanks for the update. There is a site with a similar number: `02314500`. Let me know if there is any trouble this time

**Comment by cstillwellusgs** [comment]
I've run it twice with the additional messages. The second time I cloned from scratch and re-ran the whole pipeline (with the new messages). Both times it went through without a snag. So I'm not sure how to proceed.

**Review by cstillwellusgs — APPROVED** [review]
We've discussed the odd hiccups, seemingly random and inconsistent. If you want to add more messages, feel free. At a minimum, if you decide to make no changes, add a comment in the target that describes what we've seen and that suspending and restarting seems to address the snag.

**Pull request merged**
