### PR TITLE
34 eda feature vars

### PR DESCRIPTION
**Pull request by cstillwellusgs**
Adds violin plots and maps for all feature variables. Many variables are not normally distributed, but for now I plotted everything without transformations (we can discuss at a meeting).

### CODE REVIEW

**Comment by slevin75** [comment]
@cstillwellusgs Hey Charlie - is this ready for me to review yet or should I still wait?

**Comment by cstillwellusgs** [comment]
> @cstillwellusgs Hey Charlie - is this ready for me to review yet or should I still wait?

Keep waiting, sorry! Got ahead of myself here. I will have a different PR ready for you to review, hopefully later today. Combining gages into a single record is proving to be a bit more confusing than I thought it would be...

**Comment by cstillwellusgs** [comment]
@slevin75 This is ready for review!

**Review by slevin75 — APPROVED** [review]
Everything looks fine to me.

**Pull request merged**
